---
- name: Préparation du système pour K3s
  hosts: control_plane,workers
  become: true
  tasks:

    - name: Désactiver le swap immédiatement
      command: swapoff -a
      changed_when: false

    - name: Commenter les lignes de swap dans /etc/fstab pour désactivation persistante
      replace:
        path: /etc/fstab
        regexp: '^\s*([^#].*\s+swap\s+.*)$'
        replace: '# \1'

    - name: Charger les modules overlay & br_netfilter au démarrage
      copy:
        dest: /etc/modules-load.d/k3s.conf
        content: |
          overlay
          br_netfilter
        owner: root
        group: root
        mode: '0644'

    - name: Charger les modules overlay & br_netfilter immédiatement
      shell: |
        modprobe overlay || true
        modprobe br_netfilter || true
      changed_when: false

    - name: Configurer les paramètres sysctl pour le réseau (bridge & forwarding)
      copy:
        dest: /etc/sysctl.d/99-k3s.conf
        content: |
          net.bridge.bridge-nf-call-iptables  = 1
          net.bridge.bridge-nf-call-ip6tables = 1
          net.ipv4.ip_forward                 = 1
        owner: root
        group: root
        mode: '0644'

    - name: Appliquer les paramètres sysctl
      command: sysctl --system
      changed_when: false